# Generated by Django 4.1.7 on 2023-06-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0002_alter_disciplinas_model_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register_model',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starke_app.disciplinas_model'),
        ),
    ]
