# Generated by Django 3.2.18 on 2023-06-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0002_alter_client_register_model_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas_model',
            name='profesor',
        ),
    ]
