# Generated by Django 4.1.7 on 2023-06-17 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0004_profesores_model_alter_disciplinas_model_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas_model',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starke_app.profesores_model'),
        ),
    ]
