# Generated by Django 4.1.7 on 2023-06-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0005_disciplinas_model_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register_model',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starke_app.profesores_model'),
        ),
    ]
