# Generated by Django 4.1.7 on 2023-06-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0009_remove_client_register_model_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas_model',
            name='x',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
