# Generated by Django 4.1.7 on 2023-06-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0010_disciplinas_model_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas_model',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='disciplinas_model',
            name='x',
        ),
    ]
