# Generated by Django 4.1.7 on 2023-06-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0013_disciplinas_model_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_register_model',
            name='profesor',
        ),
    ]
