# Generated by Django 4.1.7 on 2023-06-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profesores_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='disciplinas_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(blank=True, max_length=100, null=True)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starke_app.profesores_model')),
            ],
        ),
        migrations.CreateModel(
            name='client_register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('telefono_emergencia', models.IntegerField(blank=True, null=True)),
                ('nombre_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('problemas_cardiacos', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=5)),
                ('problemas_asma', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=5)),
                ('lesion_pregunta', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=5)),
                ('especificar_lesion', models.TextField(blank=True, max_length=500, null=True)),
                ('dias', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1, null=True)),
                ('plan', models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Mensual', 'Mensual'), ('Semanal', 'Semanal'), ('Diario', 'Diario')], default='Mensual', max_length=20, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('pago', models.IntegerField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starke_app.disciplinas_model')),
            ],
        ),
    ]
