# Generated by Django 4.1.7 on 2023-06-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_register_model',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_register_model',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
