# Generated by Django 3.2.18 on 2023-06-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starke_app', '0004_profesores_model_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register_model',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starke_app.profesores_model'),
        ),
    ]
